### ISSUE TITLE
Spam Video ID Submission

### ISSUE THREAD

**Issue by cochcoder** [ThioJoe/YT-Spam-Lists#455] opened 2023-09-18 18:54 UTC
### Duplicate Links

- [X] Yes, I checked that the ID **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=gk3t-2GRD5Y&lc=UgyVvVS3-OgQdRixX_h4AaABAg.9ujVV6X0J_W9ujVghIW4xb

### (Optional) Screenshot of comments using the link

![image](https://github.com/ThioJoe/YT-Spam-Lists/assets/103969142/07f48414-0ab1-4fdc-bd3b-f843d4e5de6a)

### (Required) List of the spam video IDs / Links

5qr5xvd_8tu

**Comment by Firecul** [comment] 2023-09-23 03:01
Duplicate of #452, will be added this next update

**Closed by Firecul** 2023-09-23 03:01 UTC
Labels: spam-video
