### ISSUE TITLE
Spam Video ID Submission

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spam-Lists#364] opened 2023-04-11 20:00 UTC
### Duplicate Links

- [X] Yes, I checked that the ID **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=bHn2ebchAsU&lc=UgzT8npsutpvFxdP2Rp4AaABAg.9oNZedztkxM9oNamrYswX7
https://www.youtube.com/watch?v=bHn2ebchAsU&lc=UgzfS6weltu7WkGCFYZ4AaABAg.9oNZ91RBt7n9oNZv-cFaWN
https://www.youtube.com/watch?v=4J0xFUyz1nw&lc=UgwfSv1X7Owka-9UwtJ4AaABAg.9hNi4L1_BDy9hOAWNdkDXr
https://www.youtube.com/watch?v=4J0xFUyz1nw&lc=UgxIRHr0iFPqPqfnqNh4AaABAg.9hNk2T9hxLz9hNlQGYvbsE
https://www.youtube.com/watch?v=4J0xFUyz1nw&lc=UgyEjZfa32RYyZK2TaF4AaABAg.9hPPU8vZmmk9hPX7P1AIIT
https://www.youtube.com/watch?v=_spuxXnul0U&lc=Ugy5G_p4DL7ILvCLewd4AaABAg.9e6xgdhdwu69e89OwujOi4
https://www.youtube.com/watch?v=MY4BC2Ci8hg&lc=UgztOfoFsfIEcu5e47Z4AaABAg.9gyYmp5Xeaz9gyfT6_QGZN

### (Optional) Screenshot of comments using the link

![image](https://user-images.githubusercontent.com/114196525/231274056-56031b74-9b14-4611-b29b-d6fa9d103acc.png)
![image](https://user-images.githubusercontent.com/114196525/231274103-cf32a4ad-230a-4150-bfda-8c192f0062e3.png)
![image](https://user-images.githubusercontent.com/114196525/231278028-4f2c34cb-5399-4dfb-b4fc-d2c1ab3beb82.png)
![image](https://user-images.githubusercontent.com/114196525/231279163-b4d900a4-cb13-4d6b-ac54-9e95f0d95eb2.png)
![image](https://user-images.githubusercontent.com/114196525/231280066-422b5d22-ae1c-48f5-9e0f-c7c0b136ea13.png)
![image](https://user-images.githubusercontent.com/114196525/231281663-4cb6ca16-1246-43ab-bbe9-ade45bc0c1a2.png)
![image](https://user-images.githubusercontent.com/114196525/231364575-b0250cc9-b3f0-46a6-a07b-e6e492cb5c22.png)

### (Required) List of the spam video IDs / Links

[https://youtu.be/XvF7xlZ9PWM](https://www.youtube.com/watch?v=XvF7xlZ9PWM)
[https://youtu.be/_MXe1UGClTI](https://www.youtube.com/watch?v=_MXe1UGClTI)
[https://youtu.be/HvyqYJ4Iv48](https://www.youtube.com/watch?v=HvyqYJ4Iv48)
[https://youtu.be/MrjizDdr_GE](https://www.youtube.com/watch?v=MrjizDdr_GE)
[https://youtu.be/8-nTxSt1-c8](https://www.youtube.com/watch?v=8-nTxSt1-c8)
https://www.youtube.com/watch?v=aZ12UJ1f-CE

**Comment by Firecul** [comment] 2023-04-12 23:21
I have added most of these but I'd like guidance from ThioJoe about this one.

![image](https://user-images.githubusercontent.com/114196525/231364575-b0250cc9-b3f0-46a6-a07b-e6e492cb5c22.png)

 The video it's self isn't actually spammy like the rest, the problem is this link is also a playlist. In this case I'd say the playlist was the spammy part. Would the script handle this ok without changes atm?

**Comment by Firecul** [comment] 2023-04-23 21:02
I've left this open for ThioJoe's answer to my question when he gets the chance @blahguy88

**Comment by ThioJoe** [comment] 2024-01-01 21:35
I'd have to check how it handles playlists but since this particular video/playlist probably isn't being spammed anymore I'll just close this and handle it the next time something similar comes up.

**Closed by ThioJoe** 2024-01-01 21:35 UTC
Labels: spam-video
